title: "Shubham Bhandare"

author: "Shubham Bhandare"

description: "Research Assistant, Centre for Policy Research | Political Economy | Elections | Caste Politics"

lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout Settings

show_excerpts: false
show_frame: false
show_sidebar: false
show_minimal: false

# Navigation Menu

navigation:
  - {file: "index.md", title: "Home", sidebaricon: home}
  - {file: "research.md", title: "Research", sidebaricon: flask}
  - {file: "cv.md", title: "CV", sidebaricon: address-card}
  - {file: "writing.md", title: "Writing", sidebaricon: pencil-alt}
  - {file: "photogallery.md", title: "Photo Gallery", sidebaricon: camera}

  footer:
  - {url: "mailto:shubham.bhandare.econ@gmail.com", title: "Email"}
  - {url: "https://github.com/shubham-econ", title: "GitHub"}
  - {url: "https://www.linkedin.com/in/shubham-bhandare-316443234", title: "LinkedIn"}
  - {url: "https://x.com/shubham_b02", title: "X"}

# Comments (disabled)

comments:
#  disqus_shortname: ""
#  isso_domain: ""

# Plugins

plugins:
  - jekyll-feed
